# title: Matchete
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
logo: /assets/images/matchete.pdf

url: https://f-wilsch.github.io/just-the-docs/

aux_links:
  GitLab repository: https://gitlab.com/matchete/matchete

color_scheme: matchete