# title: Matchete
description: Matchete webpage
theme: just-the-docs
logo: /assets/images/matchete.pdf

url: https://f-wilsch.github.io/just-the-docs/

aux_links:
  GitLab repository: https://gitlab.com/matchete/matchete

color_scheme: matchete

just_the_docs:
  include_head_custom: true

plugins:
  - jekyll-remote-include